export const equipment = [
    {
      id: 1,
      image:
        "https://media.istockphoto.com/id/1313613621/photo/mountain-skis-and-poles.jpg?s=612x612&w=0&k=20&c=NvZltUOGKj8xcqEbJIPwq0LCwSxaeBeRAerCC7yJ2_A=",
      title: "Xbox Matt One Controller",
      category: "Лыжи",
      price: 49.99,
      oldPrice: 99.99,
      discount: "50%",
      special: false,
      amount: 50,
      size: '130см',
      brand: 'Salamon',
      status: 'Стандарт',
      color: 'Черный',
      gender: 'Универсал',
    },
    {
      id: 2,
      image:
        "https://media.istockphoto.com/id/183861703/photo/ski-wear-equpment.jpg?s=612x612&w=0&k=20&c=KC4rzQztgd4QxzCuVmzzVaSx1ZaFRi2-VzT-trDrHE4=",
      title: "Car Air Purifier",
      category: "Ботинки",
      price: 19.99,
      special: false,
      amount: 50,
      size: '42',
      brand: 'Atomic',
      status: 'Премиум',
      color: 'Серый',
      gender: 'Мужской',
    },
    {
      id: 3,
      image:
        "https://media.istockphoto.com/id/1222223285/photo/snowboarding-and-skiing-protective-gear-and-winter-extreme-sports-concept-with-ski-goggles.jpg?s=612x612&w=0&k=20&c=fzOchfVMIowZkdJTRcNcljChow-FWzSLyhJgJihVovo=",
      title: "JBL Wireless Headphones",
      category: "Очки",
      price: 71.69,
      special: false,
      amount: 50,
      size: '',
      brand: '',
      status: 'Стандарт',
      color: 'Оранжевый',
      gender: 'Универсал',
    },
    {
      id: 4,
      image:
        "https://media.istockphoto.com/id/182149565/photo/carving-ski.jpg?s=612x612&w=0&k=20&c=GBLiP4DRXa-CdOp_lMGtXufeGKViJjsuOyLdinI16l4=",
      title: "Polaroid Snap Touch",
      category: "Лыжи",
      price: 99.89,
      special: false,
      amount: 50,
      size: '150см',
      brand: 'Ficher',
      status: 'Вип',
      color: 'Желтый',
      gender: 'Универсал',
    },
    {
      id: 5,
      image:
        "https://media.istockphoto.com/id/1220738056/photo/snowboard-clothes-and-avalanche-equipment.jpg?s=612x612&w=0&k=20&c=05YoNCMkOYnNoyAmawikcBaByHhHHrW-sRzilwVWHGc=",
      title: "Apple mini Smart Speaker",
      category: "Комплекты",
      price: 98.69,
      special: false,
      amount: 50,
      size: '',
      brand: '',
      status: '',
      color: '',
      gender: '',
    },
    {
      id: 6,
      image:
        "https://media.istockphoto.com/id/174658555/photo/snowboard-equipment.jpg?s=612x612&w=0&k=20&c=fmVTr2KecjuXZw4xVZ3FTWDEthHaRml_cUvfaed9cYc=",
      title: "Apple iPhone 13 Pro",
      category: "Сноуборды",
      price: 999.99,
      special: true,
      amount: 50,
      size: '130см',
      brand: 'Atom',
      status: 'Премиум',
      color: 'Красный',
      gender: 'Универсал',
    },
  ];